object Versions {
    const val ANDROIDX_ACTIVITY      = "1.7.0"
    const val ANDROIDX_COMPOSE       = "1.4.3"
    const val ANDROIDX_CORE          = "1.10.1"
    const val ANDROIDX_LIFECYCLE     = "2.6.1"
    const val ANDROIDX_ROOM          = "2.5.2"
    const val ANDROIDX_TEST_ESPRESSO = "3.5.1"
    const val ANDROIDX_TEST_EXT      = "1.1.5"
    const val ANDROID_GRADLE         = "8.0.0"
    const val COMPOSE_LOTTIE         = "6.1.0"
    const val DATASTORE_PREFERENCES  = "1.0.0"
    const val HILT                   = "2.48"
    const val INFO_BAR               = "1.0.0"
    const val JUNIT                  = "4.13.2"
    const val KOTLIN                 = "1.8.10"
    const val KOTLIN_COROUTINES      = "1.6.4"
    const val KSP                    = "1.8.10-1.0.9"
    const val MATERIAL               = "1.0.1"
    const val NAVIGATION_COMPOSE     = "2.6.0"
    const val NAVIGATION_HILT        = "1.0.0"
    const val PICKER_SNAPPER         = "0.3.0"
}