object Libs {
    const val ANDROIDX_ACTIVITY              = "androidx.activity:activity-compose:${Versions.ANDROIDX_ACTIVITY}"
    const val ANDROIDX_COMPOSE               = "androidx.compose.ui:ui:${Versions.ANDROIDX_COMPOSE}"
    const val ANDROIDX_CORE_KTX              = "androidx.core:core-ktx:${Versions.ANDROIDX_CORE}"
    const val ANDROIDX_LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.ANDROIDX_LIFECYCLE}"
    const val ANDROIDX_ROOM_COMPILER         = "androidx.room:room-compiler:${Versions.ANDROIDX_ROOM}"
    const val ANDROIDX_ROOM_KTX              = "androidx.room:room-ktx:${Versions.ANDROIDX_ROOM}"
    const val ANDROIDX_ROOM_RUNTIME          = "androidx.room:room-runtime:${Versions.ANDROIDX_ROOM}"
    const val ANDROIDX_TEST_ESPRESSO         = "androidx.test.espresso:espresso-core:${Versions.ANDROIDX_TEST_ESPRESSO}"
    const val ANDROIDX_TEST_EXT_JUNIT        = "androidx.test.ext:junit:${Versions.ANDROIDX_TEST_EXT}"
    const val ANDROIDX_VIEWMODEL             = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.ANDROIDX_LIFECYCLE}"
    const val COMMONS_CODEC                  = "commons-codec:commons-codec:${Versions.COMMONS_CODEC}"
    const val COMPOSE_JUNIT                  = "androidx.compose.ui:ui-test-junit4:${Versions.ANDROIDX_COMPOSE}"
    const val COMPOSE_LOTTIE                 = "com.airbnb.android:lottie-compose:${Versions.COMPOSE_LOTTIE}"
    const val COMPOSE_MANIFEST               = "androidx.compose.ui:ui-test-manifest:${Versions.ANDROIDX_COMPOSE}"
    const val COMPOSE_MATERIAL               = "androidx.compose.material3:material3:${Versions.MATERIAL}"
    const val COMPOSE_PREVIEW                = "androidx.compose.ui:ui-tooling-preview:${Versions.ANDROIDX_COMPOSE}"
    const val COMPOSE_TOOLING                = "androidx.compose.ui:ui-tooling:${Versions.ANDROIDX_COMPOSE}"
    const val DATASTORE_PREFERENCES          = "androidx.datastore:datastore-preferences:${Versions.DATASTORE_PREFERENCES}"
    const val HILT_ANDROID                   = "com.google.dagger:hilt-android:${Versions.HILT}"
    const val HILT_ANDROID_COMPILER          = "com.google.dagger:hilt-android-compiler:${Versions.HILT}"
    const val JUNIT                          = "junit:junit:${Versions.JUNIT}"
    const val KOTLIN_COROUTINES              = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.KOTLIN_COROUTINES}"
    const val NAVIGATION_COMPOSE             = "androidx.navigation:navigation-compose:${Versions.NAVIGATION_COMPOSE}"
    const val NAVIGATION_HILT                = "androidx.hilt:hilt-navigation-compose:${Versions.NAVIGATION_HILT}"
    const val PICKER_SNAPPER                 = "dev.chrisbanes.snapper:snapper:${Versions.PICKER_SNAPPER}"
}