object Libs {
    const val ANDROIDX_CORE         = "androidx.core:core-ktx:${Versions.ANDROIDX_CORE}"
    const val COMPOSE               = "androidx.compose.ui:ui:${Versions.COMPOSE}"
    const val COMPOSE_ACTIVITY      = "androidx.activity:activity-compose:${Versions.COMPOSE_ACTIVITY}"
    const val COMPOSE_LOTTIE        = "com.airbnb.android:lottie-compose:${Versions.COMPOSE_LOTTIE}"
    const val COMPOSE_MATERIAL      = "androidx.compose.material3:material3:${Versions.COMPOSE_MATERIAL}"
    const val COMPOSE_VIEWMODEL     = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.ANDROIDX_LIFECYCLE}"
    const val DATASTORE_PREFERENCES = "androidx.datastore:datastore-preferences:${Versions.DATASTORE_PREFERENCES}"
    const val HILT                  = "com.google.dagger:hilt-android:${Versions.HILT}"
    const val HILT_COMPILER         = "com.google.dagger:hilt-android-compiler:${Versions.HILT}"
    const val HILT_NAVIGATION       = "androidx.hilt:hilt-navigation-compose:${Versions.HILT_NAVIGATION}"
    const val INFO_BAR              = "com.radusalagean:info-bar-compose:${Versions.INFO_BAR}"
    const val KOTLIN_COROUTINES     = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.KOTLIN_COROUTINES}"
    const val PICKER_SNAPPER        = "dev.chrisbanes.snapper:snapper:${Versions.PICKER_SNAPPER}"
    const val ROOM                  = "androidx.room:room-ktx:${Versions.ROOM}"
    const val ROOM_COMPILER         = "androidx.room:room-compiler:${Versions.ROOM}"
    const val ROOM_RUNTIME          = "androidx.room:room-runtime:${Versions.ROOM}"
}