object Libs {
    const val ANDROIDX_CORE         = "androidx.core:core-ktx:${Versions.ANDROIDX_CORE}"
    const val ANDROIDX_ESPRESSO     = "androidx.test.espresso:espresso-core:${Versions.ANDROIDX_ESPRESSO}"
    const val ANDROIDX_JUNIT        = "androidx.test.ext:junit:${Versions.ANDROIDX_JUNIT}"
    const val COMPOSE_ACTIVITY      = "androidx.activity:activity-compose:${Versions.COMPOSE_ACTIVITY}"
    const val COMPOSE_JUNIT         = "androidx.compose.ui:ui-test-junit4:${Versions.COMPOSE}"
    const val COMPOSE_LOTTIE        = "com.airbnb.android:lottie-compose:${Versions.COMPOSE_LOTTIE}"
    const val COMPOSE_MANIFEST      = "androidx.compose.ui:ui-test-manifest:${Versions.COMPOSE}"
    const val COMPOSE_MATERIAL      = "androidx.compose.material3:material3:${Versions.COMPOSE_MATERIAL}"
    const val COMPOSE_UI            = "androidx.compose.ui:ui:${Versions.COMPOSE}"
    const val COMPOSE_VIEWMODEL     = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.ANDROIDX_LIFECYCLE}"
    const val COROUTINES            = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.COROUTINES}"
    const val COROUTINES_TEST       = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.COROUTINES}"
    const val DATASTORE_PREFERENCES = "androidx.datastore:datastore-preferences:${Versions.DATASTORE_PREFERENCES}"
    const val HILT                  = "com.google.dagger:hilt-android:${Versions.HILT}"
    const val HILT_COMPILER         = "com.google.dagger:hilt-android-compiler:${Versions.HILT}"
    const val HILT_NAVIGATION       = "androidx.hilt:hilt-navigation-compose:${Versions.HILT_NAVIGATION}"
    const val HILT_TESTING          = "com.google.dagger:hilt-android-testing:${Versions.HILT}"
    const val INFO_BAR              = "com.radusalagean:info-bar-compose:${Versions.INFO_BAR}"
    const val JUNIT                 = "junit:junit:${Versions.JUNIT}"
    const val PICKER_SNAPPER        = "dev.chrisbanes.snapper:snapper:${Versions.PICKER_SNAPPER}"
    const val ROOM                  = "androidx.room:room-ktx:${Versions.ROOM}"
    const val ROOM_COMPILER         = "androidx.room:room-compiler:${Versions.ROOM}"
    const val ROOM_RUNTIME          = "androidx.room:room-runtime:${Versions.ROOM}"
    const val SPLASH_SCREEN         = "androidx.core:core-splashscreen:${Versions.SPLASH_SCREEN}"
    const val TRUTH                 = "com.google.truth:truth:${Versions.TRUTH}"
}
