object Versions {
    const val ANDROIDX_CORE         = "1.12.0"
    const val ANDROIDX_ESPRESSO     = "3.5.1"
    const val ANDROIDX_JUNIT        = "1.1.5"
    const val ANDROIDX_LIFECYCLE    = "2.6.2"
    const val COMPOSE               = "1.5.1"
    const val COMPOSE_ACTIVITY      = "1.8.2"
    const val COMPOSE_LOTTIE        = "6.1.0"
    const val COMPOSE_MATERIAL      = "1.1.2"
    const val COROUTINES            = "1.7.1"
    const val DATASTORE_PREFERENCES = "1.0.0"
    const val HILT                  = "2.48"
    const val HILT_NAVIGATION       = "1.1.0"
    const val INFO_BAR              = "1.0.0"
    const val JUNIT                 = "4.13.2"
    const val KSP                   = "1.9.0-1.0.13"
    const val PICKER_SNAPPER        = "0.3.0"
    const val ROOM                  = "2.5.2"
    const val SPLASH_SCREEN         = "1.0.1"
    const val TRUTH                 = "1.1.5"
}