object Versions {
    const val ANDROIDX_ACTIVITY      = "1.5.1"
    const val ANDROIDX_COMPOSE       = "1.4.1"
    const val ANDROIDX_CORE          = "1.9.0"
    const val ANDROIDX_LIFECYCLE     = "2.6.1"
    const val ANDROIDX_ROOM          = "2.5.1"
    const val ANDROIDX_TEST_ESPRESSO = "3.5.1"
    const val ANDROIDX_TEST_EXT      = "1.1.5"
    const val ANDROID_GRADLE         = "7.4.1"
    const val COMMONS_CODEC          = "1.15"
    const val HILT                   = "2.45"
    const val JUNIT                  = "4.13.2"
    const val KOTLIN                 = "1.8.0"
    const val MATERIAL               = "1.0.1"
    const val PICKER_SNAPPER         = "0.3.0"
}